"""Sensor that detects dbt Cloud project changes and refreshes Dagster definitions state.

When dbt Cloud projects change (new models, modified SQL, schema changes),
Dagster's cached definitions state becomes stale. This sensor polls dbt Cloud
for new successful runs, compares the manifest fingerprint (node IDs + checksums)
to detect actual project structure changes, and triggers a targeted
`dg plus deploy refresh-defs-state` for only the affected workspace.

Required environment variables (for dbt Cloud API access):
  DBT_CLOUD_ACCOUNT_ID  - dbt Cloud account ID
  DBT_CLOUD_TOKEN       - dbt Cloud API token (shared with workspace components)
  DBT_CLOUD_ACCESS_URL  - dbt Cloud access URL (default: https://cloud.getdbt.com)

Dagster Cloud automatically provides:
  DAGSTER_CLOUD_DEPLOYMENT_NAME  - current deployment name
  DAGSTER_CLOUD_ORGANIZATION     - organization name

The `dg plus deploy refresh-defs-state` CLI picks up both automatically,
so no extra configuration is needed when running in Dagster Cloud.

Workspace project/environment IDs are configured in the WORKSPACES list below.
"""

import hashlib
import json
import subprocess
from datetime import datetime, timedelta, timezone
from typing import Any

import dagster as dg

# ── Configuration ────────────────────────────────────────────────────────────
# Each entry is a dbt Cloud workspace to monitor for project structure changes.
# - project_id / environment_id: the actual IDs (ints), or env var names (str)
# - defs_state_key: matches the pattern DbtCloudComponent[{project_id}-{environment_id}]
#   used by DbtCloudComponent.defs_state_config. Override if you customized it.

WORKSPACES: list[dict[str, Any]] = [
    {
        "name": "silver",
        "project_id_env": "DBT_CLOUD_SILVER_PROJECT_ID",
        "environment_id_env": "DBT_CLOUD_SILVER_ENVIRONMENT_ID",
    },
    {
        "name": "gold",
        "project_id_env": "DBT_CLOUD_GOLD_PROJECT_ID",
        "environment_id_env": "DBT_CLOUD_GOLD_ENVIRONMENT_ID",
    },
]

# How often to check (seconds). 5 minutes is a reasonable default.
POLL_INTERVAL_SECONDS = 300


# ── Helpers ──────────────────────────────────────────────────────────────────


def _get_dbt_cloud_client():
    """Build a DbtCloudWorkspaceClient from environment variables."""
    import os

    from dagster_dbt.cloud_v2.client import DbtCloudWorkspaceClient

    return DbtCloudWorkspaceClient(
        account_id=int(os.environ["DBT_CLOUD_ACCOUNT_ID"]),
        token=os.environ["DBT_CLOUD_TOKEN"],
        access_url=os.getenv("DBT_CLOUD_ACCESS_URL", "https://cloud.getdbt.com"),
        request_max_retries=3,
        request_retry_delay=0.25,
        request_timeout=15,
    )


def _get_latest_successful_run(
    client, project_id: int, environment_id: int
) -> dict[str, Any] | None:
    """Get the most recent successful run for a workspace."""
    now = datetime.now(tz=timezone.utc)
    lower_bound = now - timedelta(hours=24)

    try:
        runs, _ = client.get_runs_batch(
            project_id=project_id,
            environment_id=environment_id,
            finished_at_lower_bound=lower_bound,
            finished_at_upper_bound=now,
            offset=0,
        )
    except Exception:
        return None

    successful = [r for r in runs if r.get("status") == 10]  # 10 = Success
    if not successful:
        return None

    return max(successful, key=lambda r: r.get("finished_at", ""))


def _compute_manifest_fingerprint(manifest: dict[str, Any]) -> str:
    """Compute a fingerprint of the dbt manifest's project structure.

    Hashes the set of node unique_ids and their file checksums. This detects:
    - New models added
    - Models removed
    - SQL or config changes to existing models
    - Source definition changes

    Does NOT trigger on run results or metadata-only changes (timestamps, etc).
    """
    parts: list[str] = []

    for node_id in sorted(manifest.get("nodes", {})):
        node = manifest["nodes"][node_id]
        checksum = node.get("checksum", {}).get("checksum", "")
        parts.append(f"{node_id}:{checksum}")

    for source_id in sorted(manifest.get("sources", {})):
        source = manifest["sources"][source_id]
        checksum = source.get("checksum", {}).get("checksum", "")
        parts.append(f"{source_id}:{checksum}")

    content = "\n".join(parts)
    return hashlib.sha256(content.encode()).hexdigest()[:16]


def _get_defs_state_key(project_id: int, environment_id: int) -> str:
    """Derive the defs-state-key for a DbtCloudComponent workspace.

    Matches the key generated by DbtCloudComponent.defs_state_config:
        DbtCloudComponent[{project_id}-{environment_id}]
    """
    return f"DbtCloudComponent[{project_id}-{environment_id}]"


def _trigger_targeted_refresh(
    context: dg.SensorEvaluationContext,
    defs_state_key: str,
) -> bool:
    """Run dg plus deploy refresh-defs-state for a specific component.

    In Dagster Cloud, the CLI automatically reads DAGSTER_CLOUD_DEPLOYMENT_NAME
    and DAGSTER_CLOUD_ORGANIZATION from the environment.
    """
    cmd = [
        "dg", "plus", "deploy", "refresh-defs-state",
        "--defs-state-key", defs_state_key,
    ]

    context.log.info(f"Triggering targeted refresh: {' '.join(cmd)}")

    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
        if result.returncode == 0:
            context.log.info(
                f"Refresh completed for {defs_state_key}.\n{result.stdout}"
            )
            return True
        else:
            context.log.error(
                f"Refresh failed for {defs_state_key} "
                f"(exit {result.returncode}): {result.stderr}"
            )
            return False
    except subprocess.TimeoutExpired:
        context.log.error(f"Refresh timed out for {defs_state_key}.")
        return False
    except FileNotFoundError:
        context.log.error("'dg' CLI not found. Is dagster-dg-cli installed?")
        return False


# ── Sensor ───────────────────────────────────────────────────────────────────


@dg.sensor(
    name="dbt_cloud_state_refresh_sensor",
    description=(
        "Monitors dbt Cloud workspaces for project structure changes (new models, "
        "modified SQL, schema updates). Compares manifest fingerprints to detect "
        "real changes — routine runs that don't alter the project are ignored. "
        "When a change is detected, triggers a targeted "
        "`dg plus deploy refresh-defs-state --defs-state-key ...` for only the "
        "affected workspace."
    ),
    minimum_interval_seconds=POLL_INTERVAL_SECONDS,
    default_status=dg.DefaultSensorStatus.STOPPED,
)
def dbt_cloud_state_refresh_sensor(context: dg.SensorEvaluationContext):
    import os

    # Cursor: {workspace_name: {run_id: int, fingerprint: str}}
    cursor: dict[str, dict[str, Any]] = (
        json.loads(context.cursor) if context.cursor else {}
    )

    client = _get_dbt_cloud_client()
    refreshed_workspaces: list[str] = []

    for ws in WORKSPACES:
        project_id_str = os.getenv(ws["project_id_env"], "")
        environment_id_str = os.getenv(ws["environment_id_env"], "")

        if not project_id_str or not environment_id_str:
            context.log.warning(
                f"Skipping workspace '{ws['name']}': "
                f"{ws['project_id_env']} or {ws['environment_id_env']} not set."
            )
            continue

        project_id = int(project_id_str)
        environment_id = int(environment_id_str)

        latest_run = _get_latest_successful_run(client, project_id, environment_id)
        if latest_run is None:
            continue

        run_id = latest_run["id"]
        ws_cursor = cursor.get(ws["name"], {})

        # Skip if we've already checked this run
        if ws_cursor.get("run_id") == run_id:
            continue

        context.log.info(
            f"New run detected in workspace '{ws['name']}': "
            f"run_id={run_id} (previous: {ws_cursor.get('run_id')}). "
            f"Checking manifest for structural changes..."
        )

        # Fetch the manifest from this run and fingerprint it
        try:
            manifest = client.get_run_manifest_json(run_id)
        except Exception as e:
            context.log.warning(
                f"Could not fetch manifest for run {run_id}: {e}. Skipping."
            )
            cursor[ws["name"]] = {"run_id": run_id, "fingerprint": ws_cursor.get("fingerprint", "")}
            continue

        new_fingerprint = _compute_manifest_fingerprint(manifest)
        old_fingerprint = ws_cursor.get("fingerprint", "")

        if new_fingerprint == old_fingerprint:
            context.log.info(
                f"Workspace '{ws['name']}' manifest unchanged "
                f"(fingerprint: {new_fingerprint}). No refresh needed."
            )
            cursor[ws["name"]] = {"run_id": run_id, "fingerprint": new_fingerprint}
            continue

        context.log.info(
            f"Workspace '{ws['name']}' manifest changed: "
            f"{old_fingerprint or '(initial)'} -> {new_fingerprint}. "
            f"Triggering refresh."
        )

        defs_state_key = _get_defs_state_key(project_id, environment_id)
        success = _trigger_targeted_refresh(context, defs_state_key)

        cursor[ws["name"]] = {"run_id": run_id, "fingerprint": new_fingerprint}

        if success:
            refreshed_workspaces.append(ws["name"])

    context.update_cursor(json.dumps(cursor))

    if refreshed_workspaces:
        return dg.SensorResult(
            skip_reason=None,
            cursor=json.dumps(cursor),
        )

    return dg.SkipReason("No project structure changes detected in dbt Cloud.")


defs = dg.Definitions(sensors=[dbt_cloud_state_refresh_sensor])
